# core/agent.py

from typing import Any, Dict

from app.exceptions import AgentError, ToolError
from core.events import AgentEvent, EventType
from core.memory import MemoryManager
from core.observer import Observable
from core.registry import ToolRegistry
from core.llm_client import GeminiLLMClient


class Agent(Observable):
    """Main agent class that orchestrates the ReAct loop."""

    def __init__(
        self,
        llm_client: GeminiLLMClient,
        memory_manager: MemoryManager,
        tool_registry: ToolRegistry,
        max_iterations: int = 5,
    ) -> None:
        super().__init__()
        self._llm_client = llm_client
        self._memory_manager = memory_manager
        self._tool_registry = tool_registry
        self._max_iterations = max_iterations

    def handle_user_input(self, user_input: str) -> str:
        """
        Process user input through a Reason -> Act -> Observe loop.
        """
        try:
            self._memory_manager.add_user_message(user_input)
            self.notify(
                AgentEvent(
                    event_type=EventType.USER_MESSAGE_RECEIVED,
                    message="User message received and stored in memory.",
                    payload={"user_input": user_input},
                )
            )

            iteration_count = 0

            while iteration_count < self._max_iterations:
                iteration_count += 1

                self.notify(
                    AgentEvent(
                        event_type=EventType.LLM_REQUEST_STARTED,
                        message="Sending conversation history to Gemini.",
                        payload={"iteration": iteration_count},
                    )
                )

                llm_result = self._llm_client.generate(
                    history=self._memory_manager.get_history(),
                    tool_declarations=self._tool_registry.get_all_declarations(),
                )

                if llm_result["type"] == "final":
                    final_answer = llm_result["content"]
                    self._memory_manager.add_assistant_message(final_answer)

                    self.notify(
                        AgentEvent(
                            event_type=EventType.FINAL_RESPONSE_GENERATED,
                            message="Final response generated by the agent.",
                            payload={
                                "final_answer": final_answer,
                                "iteration": iteration_count,
                            },
                        )
                    )

                    return final_answer

                if llm_result["type"] == "tool_call":
                    tool_name = llm_result["tool_name"]
                    tool_args = llm_result["args"]

                    self.notify(
                        AgentEvent(
                            event_type=EventType.LLM_TOOL_REQUESTED,
                            message="Gemini requested a tool call.",
                            payload={
                                "tool_name": tool_name,
                                "tool_args": tool_args,
                                "iteration": iteration_count,
                            },
                        )
                    )

                    self.notify(
                        AgentEvent(
                            event_type=EventType.TOOL_EXECUTION_STARTED,
                            message=f"Executing tool: {tool_name}",
                            payload={
                                "tool_name": tool_name,
                                "tool_args": tool_args,
                            },
                        )
                    )

                    try:
                        tool_result = self._tool_registry.execute_tool(
                            tool_name, **tool_args
                        )

                        self._memory_manager.add_tool_message(
                            tool_name=tool_name,
                            content=tool_result,
                        )

                        self.notify(
                            AgentEvent(
                                event_type=EventType.TOOL_EXECUTION_SUCCEEDED,
                                message=f"Tool '{tool_name}' executed successfully.",
                                payload={
                                    "tool_name": tool_name,
                                    "tool_args": tool_args,
                                    "tool_result": tool_result,
                                },
                            )
                        )

                    except ToolError as exc:
                        error_result = {
                            "status": "error",
                            "tool": tool_name,
                            "error": str(exc),
                        }

                        self._memory_manager.add_tool_message(
                            tool_name=tool_name,
                            content=error_result,
                        )

                        self.notify(
                            AgentEvent(
                                event_type=EventType.TOOL_EXECUTION_FAILED,
                                message=f"Tool '{tool_name}' failed.",
                                payload={
                                    "tool_name": tool_name,
                                    "tool_args": tool_args,
                                    "error": str(exc),
                                },
                            )
                        )

                        continue

            raise AgentError(
                f"Maximum iteration limit ({self._max_iterations}) reached without final answer."
            )

        except Exception as exc:
            self.notify(
                AgentEvent(
                    event_type=EventType.AGENT_ERROR,
                    message="Agent encountered an unrecoverable error.",
                    payload={"error": str(exc)},
                )
            )
            raise
